FIND_PATH(
  INTL_INCLUDE_DIR
  NAMES 
    libintl.h
)

FIND_LIBRARY(
  INTL_LIBRARY
  NAMES
    intl
)

SET(INTL_LIBRARIES ${INTL_LIBRARY})
SET(INTL_INCLUDE_DIRS ${INTL_INCLUDE_DIR})

INCLUDE (FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Intl REQUIRED_VARS INTL_LIBRARY INTL_INCLUDE_DIR)
